### ISSUE TITLE
For images working

### ISSUE THREAD

**Issue by MansikM** [vatttanweb/APdf#3]
For images working:
Add to file /vatttan/apdf/src/Pdf/TCPDF.php line:
use Imagick;

Add to file /vatttan/apdf/src/Pdf/includes/tcpdf_images.php line:
use Vatttan\Apdf\Pdf\includes\tcpdf_static;

If you use base64 img you must replace 'data:image/png;base64,' with '@'
It must be looks like:
from
`<img src="data:image/png;base64,iVBORw0KGgoAAAANS......" />`
to
`<img src="@iVBORw0KGgoAAAANS......" />`

**Comment by AkbarDizaji** [comment]
Of course.Because its for `php `language and not for package.`src `has a character like` /` that should be scape in string and `@` do this
